using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using FuturoDoTrabalho.Api.Enums;

namespace FuturoDoTrabalho.Api.Models
{
    // ====================================================================================
    // ENTITY: Usuario
    // ====================================================================================
    // Represents a user account in the system
    // Handles authentication, authorization, and user profile management
    // Database table: usuarios
    // ====================================================================================
    [Table("usuarios")]
    public class Usuario
    {
        // ====================
        // PRIMARY KEY
        // ====================
        // Unique identifier - auto-generated by database
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        // ====================
        // PROPERTIES
        // ====================
        // Unique username for login - max 50 characters
        [Required]
        [StringLength(50)]
        public string NomeUsuario { get; set; } = string.Empty;

        // Unique email address - must be valid email format
        [Required]
        [EmailAddress]
        [StringLength(150)]
        public string Email { get; set; } = string.Empty;

        // PBKDF2 hashed password - NEVER store passwords in plain text
        [Required]
        public string SenhaHash { get; set; } = string.Empty;

        // User's full name - max 150 characters
        [Required]
        [StringLength(150)]
        public string NomeCompleto { get; set; } = string.Empty;

        // User role/profile for authorization - see UserRole enum
        [Required]
        public UserRole Perfil { get; set; } = UserRole.Funcionario;

        // Active status - indicates if account is usable
        public bool Ativo { get; set; } = true;

        // Account creation timestamp - UTC
        public DateTime DataCriacao { get; set; } = DateTime.UtcNow;

        // Last profile update timestamp - UTC, nullable
        public DateTime? DataAtualizacao { get; set; }

        // Most recent login timestamp - UTC, nullable
        public DateTime? DataUltimoLogin { get; set; }

        // ====================
        // FOREIGN KEY RELATIONSHIPS
        // ====================
        // Foreign key to Funcionario table - optional (nullable)
        // Represents the link between user account and employee record
        public int? FuncionarioId { get; set; }

        // Navigation property - represents the associated employee record
        [ForeignKey("FuncionarioId")]
        public Funcionario? Funcionario { get; set; }
    }
}
